package com.java.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.io.Serial;
import java.io.Serializable;
import java.util.Map;

/**
 * Shared clickstream / ad interaction event (architecture section 2.1).
 *
 * <p>Boilerplate (getters/setters/constructors/builder) is generated by Lombok.
 * A no-args constructor + setters are retained for Jackson (de)serialization on
 * the Kafka path, while the generated {@code builder()} is used for safe
 * construction in application code.
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ShoppingEvent implements Serializable {

    @Serial
    private static final long serialVersionUID = 1L;

    private String eventId;
    private String tenantId;
    private String userId;
    private String sessionId;
    private String campaignId;
    private String eventType;
    private long eventTimestampMs;
    private double cost;
    private Map<String, String> customTags;
}
